# Generated by Django 2.2.7 on 2019-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='lost_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
